<a href="https://colab.research.google.com/github/wafa17/Machine_Learning/blob/master/Klasifikasi.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import csv

In [41]:
from google.colab import files
uploaded = files.upload()

Saving klasifikasi.csv to klasifikasi.csv


In [42]:
df = pd.read_csv('klasifikasi.csv')
df.shape

(18278, 8)

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18278 entries, 0 to 18277
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                18278 non-null  int64
 1   skill_curve               18278 non-null  int64
 2   skill_fk_accuracy         18278 non-null  int64
 3   skill_long_passing        18278 non-null  int64
 4   skill_ball_control        18278 non-null  int64
 5   movement_acceleration     18278 non-null  int64
 6   movement_agility          18278 non-null  int64
 7   international_reputation  18278 non-null  int64
dtypes: int64(8)
memory usage: 1.1 MB


In [44]:
df.head()

Unnamed: 0  skill_curve  ...  movement_agility  international_reputation
0           0           93  ...                93                         5
1           1           81  ...                87                         5
2           2           88  ...                96                         5
3           3           13  ...                67                         3
4           4           83  ...                95                         4

[5 rows x 8 columns]

In [45]:
df.describe()

Unnamed: 0   skill_curve  ...  movement_agility  international_reputation
count  18278.000000  18278.000000  ...      18278.000000              18278.000000
mean    9138.500000     47.325692  ...         63.504924                  1.103184
std     5276.548446     18.422991  ...         14.808380                  0.378861
min        0.000000      6.000000  ...         11.000000                  1.000000
25%     4569.250000     34.000000  ...         55.000000                  1.000000
50%     9138.500000     49.000000  ...         66.000000                  1.000000
75%    13707.750000     62.000000  ...         74.000000                  1.000000
max    18277.000000     94.000000  ...         96.000000                  5.000000

[8 rows x 8 columns]

In [30]:
x = df.drop(['international_reputation'], axis=1)
x.head()

Unnamed: 0  skill_fk_accuracy  ...  skill_ball_control  movement_agility
0           0                 94  ...                  96                93
1           1                 76  ...                  92                87
2           2                 87  ...                  95                96
3           3                 14  ...                  30                67
4           4                 79  ...                  94                95

[5 rows x 5 columns]

In [46]:
#atribut skill_moves menjadi label yang digunakan untuk klasifikasi. Dimana klasifikasi terbagi 2, ada yes (1) dan no(0)
y = df['international_reputation']
y.head()

0    5
1    5
2    5
3    3
4    4
Name: international_reputation, dtype: int64

split data menjadi data train dan data testb

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix 

In [0]:
#membagi data menjadi data test dan data train dengan perbandingan 20:80
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.3, random_state = 123)

In [0]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

**Klasifikasi menggunakan K-Nearest Neighbor**

In [51]:
#klasifikasi menggunakan KNN (library)
klasifikasi = KNeighborsClassifier(n_neighbors=5)
klasifikasi.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [52]:
# Menentukan hasil prediksi dari x_test
y_pred = klasifikasi.predict(x_test)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [53]:
# probabilitas hasil prediksi x_test
klasifikasi.predict_proba(x_test)

array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]])

In [54]:
print(confusion_matrix(y_test, y_pred))

[[4980   63    3    0    0]
 [ 267   70    9    0    0]
 [  44   14   17    0    0]
 [   4    7    3    0    0]
 [   2    0    1    0    0]]


In [55]:
#menampilkan hasil klasifikasi
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.94      0.99      0.96      5046
           2       0.45      0.20      0.28       346
           3       0.52      0.23      0.31        75
           4       0.00      0.00      0.00        14
           5       0.00      0.00      0.00         3

    accuracy                           0.92      5484
   macro avg       0.38      0.28      0.31      5484
weighted avg       0.90      0.92      0.91      5484



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [56]:
#menampilkan hasil akurasi data
from sklearn.metrics import accuracy_score
accuracyKnn= accuracy_score(y_test, y_pred)
accuracyKnn

0.9239606126914661

**KLASIFIKASI MENGGUNAKAN NAIVE BAYES**

In [0]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [0]:
#membagi data menjadi data test dan data train dengan perbandingan 20:80
x_t, x_s, y_t, y_s = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [0]:
scaler = StandardScaler()
scaler.fit(x_train)
x_t = scaler.transform(x_t)
x_s = scaler.transform(x_s)

In [60]:
# Mengaktifkan/memanggil/membuat fungsi klasifikasi Naive bayes
modelnb = GaussianNB()
# Memasukkan data training pada fungsi klasifikasi naive bayes
nbtrain = modelnb.fit(x_t, y_t)
nbtrain.class_count_

array([1.3432e+04, 9.0800e+02, 2.4400e+02, 3.5000e+01, 3.0000e+00])

In [61]:
y_p = nbtrain.predict(x_s)
y_p

array([1, 1, 2, ..., 1, 1, 1])

In [62]:
# Menentukan probabilitas hasil prediksi
nbtrain.predict_proba(x_s)

array([[1.00000000e+000, 1.91192628e-010, 8.72968464e-050,
        0.00000000e+000, 0.00000000e+000],
       [1.00000000e+000, 1.07225665e-012, 3.10329007e-067,
        0.00000000e+000, 0.00000000e+000],
       [2.26827561e-001, 7.67760187e-001, 5.41225114e-003,
        1.05558120e-037, 0.00000000e+000],
       ...,
       [9.63120814e-001, 3.68791583e-002, 2.76554792e-008,
        7.98838390e-103, 0.00000000e+000],
       [9.42998656e-001, 5.70001435e-002, 1.20037603e-006,
        2.62452992e-078, 0.00000000e+000],
       [1.00000000e+000, 1.77643650e-010, 4.46384182e-058,
        0.00000000e+000, 0.00000000e+000]])

In [63]:
confusion_matrix(y_s, y_p)

array([[3036,  311,   14,    1,    0],
       [  87,  115,   27,    3,    0],
       [  11,   15,   13,    8,    1],
       [   2,    4,    1,    1,    3],
       [   1,    0,    0,    0,    2]])

In [64]:
# Menghitung nilai akurasi dari klasifikasi naive bayes
print(classification_report(y_s,y_p))

              precision    recall  f1-score   support

           1       0.97      0.90      0.93      3362
           2       0.26      0.50      0.34       232
           3       0.24      0.27      0.25        48
           4       0.08      0.09      0.08        11
           5       0.33      0.67      0.44         3

    accuracy                           0.87      3656
   macro avg       0.37      0.49      0.41      3656
weighted avg       0.91      0.87      0.88      3656



In [65]:
from sklearn.metrics import accuracy_score
accuracyNB= accuracy_score(y_s, y_p)
accuracyNB

0.8662472647702407

In [66]:
accuracyKnn

0.9239606126914661