<a href="https://colab.research.google.com/github/wafa17/Machine_Learning/blob/master/Klasifikasi(knn%2Cnb).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import csv

In [0]:
from google.colab import files
uploaded = files.upload()

Saving dataKlasifikasi.csv to dataKlasifikasi.csv


In [0]:
df = pd.read_csv('dataKlasifikasi.csv')
df.shape

(18278, 5)

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18278 entries, 0 to 18277
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                18278 non-null  int64
 1   overall                   18278 non-null  int64
 2   international_reputation  18278 non-null  int64
 3   weak_foot                 18278 non-null  int64
 4   skill_moves               18278 non-null  int64
dtypes: int64(5)
memory usage: 714.1 KB


In [0]:
df.head()

Unnamed: 0  overall  international_reputation  weak_foot  skill_moves
0           0       94                         5          4            4
1           1       93                         5          4            5
2           2       92                         5          5            5
3           3       91                         3          3            1
4           4       91                         4          4            4

In [0]:
df.describe()

Unnamed: 0       overall  ...     weak_foot   skill_moves
count  18278.000000  18278.000000  ...  18278.000000  18278.000000
mean    9138.500000     66.244994  ...      2.944250      2.368038
std     5276.548446      6.949953  ...      0.664656      0.765038
min        0.000000     48.000000  ...      1.000000      1.000000
25%     4569.250000     62.000000  ...      3.000000      2.000000
50%     9138.500000     66.000000  ...      3.000000      2.000000
75%    13707.750000     71.000000  ...      3.000000      3.000000
max    18277.000000     94.000000  ...      5.000000      5.000000

[8 rows x 5 columns]

In [0]:
x = df.drop(['overall'], axis=1)
x.head()

Unnamed: 0  international_reputation  weak_foot  skill_moves
0           0                         5          4            4
1           1                         5          4            5
2           2                         5          5            5
3           3                         3          3            1
4           4                         4          4            4

In [0]:
#atribut overall menjadi label yang digunakan untuk klasifikasi. 
y = df['overall']
y.head()

0    94
1    93
2    92
3    91
4    91
Name: overall, dtype: int64

split data menjadi data train dan data testb

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix 

In [0]:
#membagi data menjadi data test dan data train dengan perbandingan 20:80
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [0]:
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

**Klasifikasi menggunakan K-Nearest Neighbor**

In [0]:
#klasifikasi menggunakan KNN (library)
klasifikasi = KNeighborsClassifier(n_neighbors=5)
klasifikasi.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
# Menentukan hasil prediksi dari x_test
y_pred = klasifikasi.predict(x_test)
y_pred

array([61, 57, 72, ..., 70, 70, 59])

In [0]:
# probabilitas hasil prediksi x_test
klasifikasi.predict_proba(x_test)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [0]:
print(confusion_matrix(y_test, y_pred))

[[10  0  0 ...  0  0  0]
 [ 0  9  1 ...  0  0  0]
 [ 0  0 19 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


In [0]:
#menampilkan hasil klasifikasi
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          48       1.00      0.91      0.95        11
          49       1.00      0.75      0.86        12
          50       0.95      0.86      0.90        22
          51       0.75      1.00      0.86        18
          52       0.82      0.95      0.88        42
          53       1.00      0.80      0.89        50
          54       0.98      0.98      0.98        45
          55       0.97      0.91      0.94        65
          56       0.90      0.96      0.93        77
          57       0.98      0.94      0.96        88
          58       0.98      0.98      0.98        94
          59       0.93      0.95      0.94       105
          60       0.90      0.95      0.93       127
          61       0.94      0.95      0.94       129
          62       0.98      0.95      0.96       150
          63       0.99      0.97      0.98       167
          64       0.98      0.99      0.99       237
          65       0.98    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
#menampilkan hasil akurasi data
from sklearn.metrics import accuracy_score
accuracyKnn= accuracy_score(y_test, y_pred)
accuracyKnn

0.9316192560175055

**KLASIFIKASI MENGGUNAKAN NAIVE BAYES**

In [0]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [0]:
#membagi data menjadi data test dan data train dengan perbandingan 20:80
x_t, x_s, y_t, y_s = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [0]:
scaler = StandardScaler()
scaler.fit(x_train)
x_t = scaler.transform(x_t)
x_s = scaler.transform(x_s)

In [0]:
# Mengaktifkan/memanggil/membuat fungsi klasifikasi Naive bayes
modelnb = GaussianNB()
# Memasukkan data training pada fungsi klasifikasi naive bayes
nbtrain = modelnb.fit(x_t, y_t)
nbtrain.class_count_

array([ 32.,  54.,  81.,  99., 127., 147., 187., 209., 283., 272., 391.,
       440., 574., 520., 723., 779., 901., 892., 912., 830., 869., 770.,
       722., 569., 621., 511., 403., 412., 280., 208., 194., 147., 124.,
        70.,  74.,  62.,  42.,  31.,  15.,  13.,  14.,  10.,   3.,   3.,
         1.,   1.])

In [0]:
y_p = nbtrain.predict(x_s)
y_p

array([61, 57, 72, ..., 69, 70, 59])

In [0]:
# Menentukan probabilitas hasil prediksi
nbtrain.predict_proba(x_s)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [0]:
confusion_matrix(y_s, y_p)

array([[10,  1,  0, ...,  0,  0,  0],
       [ 0, 12,  0, ...,  0,  0,  0],
       [ 0,  0, 22, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  1,  0]])

In [0]:
# Menghitung nilai akurasi dari klasifikasi naive bayes
print(classification_report(y_s,y_p))

              precision    recall  f1-score   support

          48       1.00      0.91      0.95        11
          49       0.92      1.00      0.96        12
          50       1.00      1.00      1.00        22
          51       1.00      1.00      1.00        18
          52       0.88      1.00      0.93        42
          53       1.00      0.88      0.94        50
          54       1.00      0.98      0.99        45
          55       0.97      1.00      0.98        65
          56       0.99      0.99      0.99        77
          57       0.99      0.99      0.99        88
          58       1.00      0.98      0.99        94
          59       0.99      1.00      1.00       105
          60       0.96      1.00      0.98       127
          61       1.00      0.96      0.98       129
          62       0.99      0.99      0.99       150
          63       0.98      0.99      0.99       167
          64       1.00      0.97      0.99       237
          65       0.98    

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
from sklearn.metrics import accuracy_score
accuracyNB= accuracy_score(y_s, y_p)
accuracyNB

0.9814004376367614

In [0]:
accuracyKnn

0.9316192560175055